name: Test
on:
  push:
    branches: [master, stag]
    paths:
      - '**.py'
  pull_request:
    branches: [master, stag]
    paths:
      - '**.py'
  schedule:
    - cron: "0 10 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.6'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'stag'
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Run Test
      run: |
        source scripts/test_env.sh
        sed -i '/APIGW_ENABLED/d' dev.env.yml
        pip install -r requirements.txt
        pip install coverage
        pip uninstall pycrypto -y
        pip uninstall pycryptodome -y
        pip install pycryptodome
        python manage.py test apps.tests